In [ ]:
# numpy arrays
###numirical python

In [1]:
import numpy as np
#dir(np for all directories in numpy

In [3]:
# create id numpy array
x=np.array([45,67,57,60])
print(x)
print(type(x))# class of object
print(x.dtype)# for data type of object

[45 67 57 60]
<class 'numpy.ndarray'>
int64


In [5]:
# create id numpy array
x=np.array([45,67,57,9.8])
print(x)
print(type(x))# class of object
print(x.dtype)# for data type of object

[45.  67.  57.   9.8]
<class 'numpy.ndarray'>
float64


In [7]:
# create id numpy array
x=np.array([45,67,57,60,'G'])
print(x)
print(type(x))# class of object
print(x.dtype)# for data type of object

['45' '67' '57' '60' 'G']
<class 'numpy.ndarray'>
<U21


In [15]:
# create 2d numpy array
x1=np.array([[45,67],[57,60]])
print(x1)
print(type(x1))# class of object
print(x1.shape)# for data type of object

[[45 67]
 [57 60]]
<class 'numpy.ndarray'>
(2, 2)


In [23]:
# create 1d numpy array
x=np.array([45,67,57,60])
y=x.reshape(2,2)# instead of 1,4 , 4,1
print(y)
print(type(y))# class of object
print(y.shape)# for data type of object

[[45 67]
 [57 60]]
<class 'numpy.ndarray'>
(2, 2)


In [37]:
# create an array with arange()
c=np.arange(3,11)
c1=c.reshape(4,2)
print(c)
print(c1)
type(c1)

[ 3  4  5  6  7  8  9 10]
[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


numpy.ndarray

In [41]:
# use of around()
d=np.array([1.3467,3.10987,4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [43]:
# use of np.sqrt()
d=np.array([1.3467,3.10987,4.91236])
print(d)
print(np.around(np.sqrt(d),2))

[1.3467  3.10987 4.91236]
[1.16 1.76 2.22]


In [47]:
np.sqrt(16)

np.float64(4.0)

In [51]:
# use of np.nan for showing null value
x1=np.array([[3,4,5,8],[7,2,8,np.nan]])
print(x1)
x1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [53]:
# use of np.astype() to convert the data type
x1=np.array([[3,4,5,8],[7,2,8,np.nan]])
x2=x1.astype(str)
print(x2)
x2.dtype

[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [70]:
#maths operations an rows and cols
a2=np.array([[3,4,6],[7,9,10],[4,6,12]])
print(a2)
print(a2.sum(axis=1))#for rows
a2.sum(axis=0)#for cols
a2.mean(axis=1)

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[13 26 22]


array([4.33333333, 8.66666667, 7.33333333])

In [74]:
#matrix operations
a3=np.array([[3,4,6],[7,9,10],[4,6,12]])
print(a3)
np.fill_diagonal(a3,0) #for diagonal elements
print()
print(a3)

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]

[[ 0  4  6]
 [ 7  0 10]
 [ 4  6  0]]


In [78]:
# multiply matrices
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
c=np.matmul(A,B)
print(c)

[[ 7 10]
 [15 22]]


In [80]:
# to find transopose use '.T'
print(A.T)

[[1 3]
 [2 4]]


In [92]:
# Accessing array elements
a4=np.array([[3,4,5],[7,2,8],[9,1,6],[10,9,18]])
print(a4)
print()
print(a4[2][2])#[r][c]
print(a4[2][0])

[[ 3  4  5]
 [ 7  2  8]
 [ 9  1  6]
 [10  9 18]]

6
9


In [94]:
#row slicing and col slicing
a4[1:3,0:2] #a4[row,col]

array([[7, 2],
       [9, 1]])

In [108]:
#accessing max value and its index using argmax() it say max values position
a3=np.array([[3,4,5],[7,2,8],[9,1,6]])
print(a3)
print()
print(np.argmax(a3,axis=1))
print(np.argmax(a3,axis=0))
print("amax()")# it shows max values directly
print(np.amax(a3,axis=1))
print(np.amax(a3,axis=0))

[[3 4 5]
 [7 2 8]
 [9 1 6]]

[2 2 0]
[2 0 1]
amax()
[5 8 9]
[9 4 8]


In [100]:
# amax using


[ 6 10  6]
[ 7  6 10]
