In [13]:
# svm classification
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score, StratifiedKFold

In [5]:
dataframe=pd.read_csv('diabetes.csv')
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [9]:
array=dataframe.values
x=array[:,0:8]
y=array[:,8]

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y)

In [17]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((614, 8), (614,), (154, 8), (154,))

In [19]:
clf=SVC()
clf.fit(x_train,y_train)

SVC()

In [21]:
y_predict=clf.predict(x_test)

In [29]:
# test accuracy
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

         0.0       0.79      0.91      0.85       100
         1.0       0.77      0.56      0.65        54

    accuracy                           0.79       154
   macro avg       0.78      0.73      0.75       154
weighted avg       0.78      0.79      0.78       154



In [27]:
# Train Accuracy
#accuracy_score(y_train,clf.predict(x_train))
print(classification_report(y_train,clf.predict(x_train)))

              precision    recall  f1-score   support

         0.0       0.76      0.92      0.83       400
         1.0       0.75      0.47      0.58       214

    accuracy                           0.76       614
   macro avg       0.76      0.69      0.71       614
weighted avg       0.76      0.76      0.74       614



#### Hyper Parameter Tuning with Randomized Grid Search CV

In [46]:
clf = SVC()
param_grid = [{'kernel':['linear','rbf'], 'gamma':[0.1,0.5,1], 'C':[0.1,1,10] }]
kfold = StratifiedKFold(n_splits=5)
gsv = RandomizedSearchCV(clf,param_grid,cv=kfold,scoring= 'recall')
gsv.fit(x_train,y_train)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=SVC(),
                   param_distributions=[{'C': [0.1, 1, 10],
                                         'gamma': [0.1, 0.5, 1],
                                         'kernel': ['linear', 'rbf']}],
                   scoring='recall')

In [48]:
gsv.best_params_, gsv.best_score_

({'kernel': 'linear', 'gamma': 1, 'C': 1}, 0.579734219269103)

In [66]:
clf_model = SVC(kernel='linear', C=1)
clf_model.fit(x_train, y_train)

y_pred = clf_model.predict(x_test)

acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)

confusion_matrix(y_test, y_pred)


Accuracy = 79.22077922077922


array([[90, 10],
       [22, 32]], dtype=int64)

In [57]:
y_pred

array([0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0.])

In [70]:
confusion_matrix(y_test,y_pred)

array([[90, 10],
       [22, 32]], dtype=int64)